### ISSUE TITLE
Execution terminating abruptly in long genomcmcgan runs

### ISSUE THREAD

**Issue by pabloswfly** [RacimoLab/genomcmcgan#23]
This error always appears when I try to run the mcmcgan with a higher number of mcmc samples, and it looks like it's related to `concurrent.futures` package and multicore processing. In general,  this error pops up after running genomcmcgan.py for longer than 30 - 40 minutes:

```
2020-12-10 11:53:59.338246: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Traceback (most recent call last):

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 245, in _unnormalized_log_prob
    score = self.D(proposals)

  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 222, in D
    self.discriminator.predict(self.genob.simulate_msprime(x).astype("float32"))

  File "/home/sxm614/genomcmcgan/genobuilder.py", line 194, in simulate_msprime
    for i, m in enumerate(ex.map(do_sim, args, timeout=timeout)):

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/process.py", line 629, in submit
    raise BrokenProcessPool(self._broken)

concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore


Traceback (most recent call last):
  File "genomcmcgan.py", line 263, in <module>
    run_genomcmcgan(
  File "genomcmcgan.py", line 131, in run_genomcmcgan
    is_accepted, log_acc_rate = mcmcgan.run_chain()
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 761, in __call__
    return self._python_function(*args, **kwds)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3730, in bound_method_wrapper
    return wrapped_fn(weak_instance(), *args, **kwargs)
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 336, in run_chain
    samples, [is_accepted, log_acc_rat] = tfp.mcmc.sample_chain(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/sample.py", line 358, in sample_chain
    (_, _, final_kernel_results), (all_states, trace) = mcmc_util.trace_scan(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 452, in trace_scan
    _, final_state, _, trace_arrays = tf.while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2489, in while_loop_v2
    return while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2735, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 442, in _body
    state = loop_fn(state, elem)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/sample.py", line 351, in _trace_scan_fn
    seed, next_state, current_kernel_results = mcmc_util.smart_for_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 341, in smart_for_loop
    return tf.while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2489, in while_loop_v2
    return while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2735, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 343, in <lambda>
    body=lambda i, *args: [i + 1] + list(body_fn(*args)),
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/sample.py", line 348, in _seeded_one_step
    kernel.one_step(*state_and_results, **one_step_kwargs))
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/simple_step_size_adaptation.py", line 344, in one_step
    new_state, new_inner_results = self.inner_kernel.one_step(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 573, in one_step
    next_state, kernel_results = self._impl.one_step(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 215, in one_step
    ] = self.inner_kernel.one_step(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/hmc.py", line 774, in one_step
    ] = integrator(current_momentum_parts,
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/leapfrog_integrator.py", line 282, in __call__
    ] = tf.while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2489, in while_loop_v2
    return while_loop(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2735, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/leapfrog_integrator.py", line 284, in <lambda>
    body=lambda i, *args: [i + 1] + list(_one_step(  # pylint: disable=no-value-for-parameter,g-long-lambda
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/leapfrog_integrator.py", line 325, in _one_step
    [next_target, next_target_grad_parts] = mcmc_util.maybe_call_fn_and_grads(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 293, in maybe_call_fn_and_grads
    result, grads = _value_and_gradients(fn, fn_arg_list, result, grads)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 253, in _value_and_gradients
    result = fn(*fn_arg_list)
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 250, in unnormalized_log_prob
    return tf.py_function(self._unnormalized_log_prob, inp=[x], Tout=tf.float32)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 456, in eager_py_func
    return _internal_py_func(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 337, in _internal_py_func
    result = gen_script_ops.eager_py_func(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/gen_script_ops.py", line 49, in eager_py_func
    _ops.raise_from_not_ok_status(e, name)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Traceback (most recent call last):

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 245, in _unnormalized_log_prob
    score = self.D(proposals)

  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 222, in D
    self.discriminator.predict(self.genob.simulate_msprime(x).astype("float32"))

  File "/home/sxm614/genomcmcgan/genobuilder.py", line 194, in simulate_msprime
    for i, m in enumerate(ex.map(do_sim, args, timeout=timeout)):

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/process.py", line 674, in map
    results = super().map(partial(_process_chunk, fn),

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]

  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/process.py", line 629, in submit
    raise BrokenProcessPool(self._broken)

concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

 [Op:EagerPyFunc]
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f42382c8bb0>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 435, in trace_one_step
    return tf.nest.map_structure(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 634, in map_structure
    return pack_sequence_as(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 436, in <lambda>
    lambda ta, x: ta.write(num_steps_traced, x),  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f42100a5fd0>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 435, in trace_one_step
    return tf.nest.map_structure(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 634, in map_structure
    return pack_sequence_as(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 436, in <lambda>
    lambda ta, x: ta.write(num_steps_traced, x),  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f41e0796f40>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 435, in trace_one_step
    return tf.nest.map_structure(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 634, in map_structure
    return pack_sequence_as(  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 436, in <lambda>
    lambda ta, x: ta.write(num_steps_traced, x),  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
```

Run on the latest version of the software, with the command:

`python genomcmcgan.py test.pkl -d test_data.pkl -k hmc -e 3 -n 400 -b 100 -se 1234 -p 64`

In this case, the execution got truncated in the middle of the mcmc sampling in the second genomcmcgan training iteration.

**Comment by grahamgower** [comment]
It's possible there's a memory/resource leak somewhere.  I noticed I couldn't run very long chains on my laptop without running out of memory. Does the memory usage increase towards the maximum even on the server?

**Comment by pabloswfly** [comment]
Yes, the process that hosts the running script gradually and steadily increases the memory usage and never decreasing. All the subprocesses created with -parallelism occupy a stable 0,8% of memory each when run on 64 cores.

```
top - 12:44:16 up 33 days, 20:58,  2 users,  load average: 19,21, 18,42, 11,04
Tasks: 874 total,   2 running, 872 sleeping,   0 stopped,   0 zombie
%Cpu(s): 27,5 us,  3,5 sy,  0,0 ni, 62,8 id,  6,3 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 79176345+total, 52166889+free, 26781409+used,  2280456 buff/cache
KiB Swap:  4194300 total,      256 free,  4194044 used. 52196675+avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                          
122348 sxm614    20   0  289,2g 236,6g 665656 R 462,9 31,3  55:16.86 python                                                                                           
122931 sxm614    20   0   58,6g   5,7g 367940 S  36,4  0,8   2:59.38 python                                                                                           
122963 sxm614    20   0   58,6g   5,7g 367940 S  36,4  0,8   2:57.70 python                                                                                           
122901 sxm614    20   0   58,6g   5,7g 367940 S  35,4  0,8   2:53.13 python                                                                                           
122938 sxm614    20   0   58,6g   5,7g 367932 S  35,4  0,8   3:05.31 python                                                                                           
122926 sxm614    20   0   58,6g   5,7g 367940 S  35,1  0,8   3:01.05 python                                                                                           
122955 sxm614    20   0   58,6g   5,7g 367932 S  34,8  0,8   2:59.42 python                                                                                           
122920 sxm614    20   0   58,6g   5,7g 367940 S  34,4  0,8   3:01.51 python                                                                                           
122922 sxm614    20   0   58,6g   5,7g 367940 S  34,4  0,8   2:58.64 python 
... 
```

**Comment by grahamgower** [comment]
That's crazy!

**Comment by pabloswfly** [comment]
In which sense?

**Comment by grahamgower** [comment]
That it uses so much memory. I'll definitely take a look at that today or tomorrow.

**Comment by grahamgower** [comment]
Well I still have no idea how to deal with this, but it seems to be caused by repeatedly calling `discriminator.predict()`. Possibly also a problem caused by calling it from within the "eagerly executed" log_prob function. Definitely a tensorflow bug. Definitely already reported by numerous people working with GANs.

https://github.com/tensorflow/tensorflow/issues/33030
https://github.com/keras-team/keras/issues/13118
https://github.com/tensorflow/tensorflow/issues/35010

[EDIT: and the problem still exists with tensorflow `2.4.0-rc4`]

**Comment by pabloswfly** [comment]
True, by commenting out the `discriminator.predict()` part, returning a random number instead and checking memory usage with htop, the memory does not increase anymore. 

I recall finding similar posts when I was stuck with the Tensorflow error I had before submitting my master thesis. I will try several workarounds suggested in those posts, as it seems the bug won't be fixed by TF team anytime soon if the problem dates back to 2019.

**Comment by grahamgower** [comment]
None of the workarounds suggested worked for me. I wanted to try putting the `descriminator.predict()` call in its own process too, but that creates a new problem (the process just freezes)!

**Comment by grahamgower** [comment]
Here's some example code to show what freezes. (modified from https://github.com/tensorflow/tensorflow/issues/39431)
```python
import concurrent.futures
import tensorflow as tf
import numpy as np

def predict(data):
    tf.keras.backend.clear_session()
    tf.compat.v1.reset_default_graph()
    mdl = tf.keras.Sequential([tf.keras.layers.Dense(4, input_shape=(16,))])
    print("predict 1")
    res = mdl.predict(data)
    print("predict 2")
    return res

fake_data = np.zeros((100, 16))

# Works.
print(predict(fake_data).shape)

# Never finishes running.
# But comment out the previous direct call to predict, and this works fine.
with concurrent.futures.ProcessPoolExecutor(max_workers=1) as ex:
    pred = next(ex.map(predict, [fake_data]))
print(pred.shape)
```

So we'd need to move all the code that constructs/fits/predicts the discriminator into separate processes. What a pain! I don't see any other way around the issue though. As you say, the TF team don't seem to care about fixing these issues with global state (both memory leak and this freezing problem are caused by TF having global state instead of per-process state).

**Comment by grahamgower** [comment]
I'm going to hack around the issues, and get something working today. We can worry about making it look nice and clean once it's working...

**Comment by pabloswfly** [comment]
Ouch! It doesn't sound very straightforward. I've run the code snippet and saw what you mean. 
So basically `ProcessPoolExecutor()` context manager is needed every time the discriminator model is called within the code?

I will finish implementing the new demographic models with more parameters to infer, and I'll jump also  into this issue.

**Comment by grahamgower** [comment]
> So basically `ProcessPoolExecutor()` context manager is needed every time the discriminator model is called within the code?

Yeah. Except it seems like we need to do this for every bit of code that uses tensorflow. So, it's basically impossible, because the GAN needs to call predict(), and we can't put the mcmc chain itself in a separate process which makes new processes for `predict()`, without having the `predict()` processes hang. So, fuck you tensorflow!

Maybe we should just save the chain, and permit restarting from the end of the chain when the program has been killed because it ran out of memory.

**Comment by pabloswfly** [comment]
Damn, this really sucks. That sounds like one of the few viable options.

How feasible do you think it is If I try to translate the whole project from TF to PyTorch? PyTorch neural nets building doesn't seem much more complicated than a Keras model ([see here](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html)), and the MCMC capabilities can be implemented with Pyro, which is a Probabilistic Programming Language (PPL) that uses PyTorch as the backend ([see here](http://docs.pyro.ai/en/0.2.1-release/mcmc.html)).

**Comment by grahamgower** [comment]
I think it would be easier to replace only the MCMC component, with a regular CPU-based implementation. The discriminator's `predict()` function could then live in it's own process without problem.

**Comment by grahamgower** [comment]
Care to try something like https://github.com/wgurecky/bipymc or https://github.com/LoLab-VU/PyDREAM along with the changes I made in #24?

**Comment by grahamgower** [comment]
Here's a list of MCMC packages. Lots of them want gradients specified.
https://github.com/Gabriel-p/pythonMCMC

This one doesn't require a gradient function, looks very simple to use, and is also properly documented.
https://emcee.readthedocs.io/en/stable/
And there's a NUTS sampler for it too.
https://github.com/mfouesneau/NUTS

**Comment by pabloswfly** [comment]
Thanks for the pointers! Sure, I'll check which one looks the most appropriate and I will start working on the migration.

**Comment by grahamgower** [comment]
Oh, and you might be able to use this to calculate the gradients numerically, if you really do want to use an MCMC that explicitly asks for a gradient function. It's better if the MCMC package does this itself though, because it's possible for the MCMC to call the log_prob() function fewer times (e.g. i think tensorflow does this).
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html

**Comment by grahamgower** [comment]
One more to consider. Strangely, it looks both new and discontinued.
https://github.com/eigenfoo/littlemcmc

**Comment by pabloswfly** [comment]
Cool! This last one looks lightweight, containing just the HMC and NUTS sampler that is what we're aiming for. However, it requires to specify the gradient function, which I can try to do with your suggested `scipy.optimize.approx_fprime()`.
Otherwise, I will try `emcee`'s implementation.

PS. The memory leak still persists on the new stable TF 2.4 version which came out yesterday.

**Comment by pabloswfly** [comment]
I have implemented the NUTS and HMC samplers from `littlemcmc` library, and started the experiments on the inference of just a single parameter (recombination rate). The discriminator model is compiled and trained correctly. However, the code gets stuck at the first sampling step. The log from this error:

```
Starting the MCMC sampling chain
Selected mcmc kernel is hmc
Only 100 samples in chain.
1e-10------------------| 0.00% [0/200 00:00<00:00 Sampling chain 0, 0 divergences]
r: 1e-10
Failed to initialize GPU device #0: initialization error
Failed to initialize GPU device #1: initialization error
Failed to initialize GPU device #2: initialization error
Failed to initialize GPU device #3: initialization error
Failed to initialize GPU device #4: initialization error
2020-12-16 12:21:48.005502: F tensorflow/stream_executor/cuda/cuda_driver.cc:219] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error
Traceback (most recent call last):
  File "genomcmcgan.py", line 215, in <module>
    run_genomcmcgan(
  File "genomcmcgan.py", line 100, in run_genomcmcgan
    stats = mcmcgan.run_chain()
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 318, in run_chain
    trace, stats = lmc.sample(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/sampling.py", line 205, in sample
    traces, stats = _sample_many(**sample_args)  # type: ignore
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/sampling.py", line 371, in _sample_many
    trace, stats_ = _sample(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/sampling.py", line 464, in _sample
    for it, (trace, stats) in enumerate(sampling):
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/fastprogress/fastprogress.py", line 47, in __iter__
    raise e
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/fastprogress/fastprogress.py", line 41, in __iter__
    for i,o in enumerate(self.gen):
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/sampling.py", line 512, in _iter_sample
    q, step_stats = step._astep(q)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/base_hmc.py", line 143, in _astep
    start = self.integrator.compute_state(q0, p0)
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/site-packages/littlemcmc/integration.py", line 62, in compute_state
    logp, dlogp = self._logp_dlogp_func(q)
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 269, in logp_dlogp
    return self.log_prob(x), self.dlog_prob(x)
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 260, in log_prob
    score = self.D(proposals)
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 246, in D
    return np.mean(self.discriminator.predict(self.genob.simulate_msprime(x)))
  File "/home/sxm614/genomcmcgan/mcmcgan.py", line 221, in predict
    preds = next(
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/sxm614/miniconda3/envs/geno2env/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

I tried different versions of Cudatoolkit and CudNN with no results. The problem seems to originate from a conflict between the Keras discriminator model and the multiprocessing method during sampling. Following this [post,](https://stackoverflow.com/questions/42504669/keras-tensorflow-and-multiprocessing-in-python), I've tried to import Keras only inside the environment of the corresponding functions, but didn't work.

I am using `TF==3.2.1`, `Cudatoolkit==10.1.243` and `cuDNN==7.6.5`

**Comment by pabloswfly** [comment]
Apparently I've fixed this issue, by also importing TensorFlow exclusively inside the multi-processing functions and not globally.
However, it looks like it is extremely slow now. I will do more analysis and update on this.

**Comment by grahamgower** [comment]
Ok, I think I fixed that by removing *all* the `keras` and `tf` imports from the main process. They only get imported in the subprocesses now. There's another error from littlemcmc now (I guess some parameter needs to be a numpy array, not a list)

**Comment by grahamgower** [comment]
You beat me by 10 seconds!

**Comment by pabloswfly** [comment]
Thanks for the help, that was coordination!

**Comment by grahamgower** [comment]
It seems the speed is now limited to the tensorflow startup time. \*sigh\*

Maybe we could start a subprocess that just calls the discriminator, and pass the input/output to the subprocess via a pipe, then kill the process after (say) 100 predict() calls, and restart the subprocess for the next set of predict() calls. What a total nightmare!

Also, any idea how to restart the chain with littlemcmc? I guess there's some internal state in the sampler that needs to be saved (e.g. momentum params and so forth)?

**Comment by pabloswfly** [comment]
Right, I feel we are deconstructing something that was already beautiful. My HMC sampling only collected 11 samples in around 2 hours running. For Christmas, I'm asking for a miraculous update on the `predict()` function from the TF team, beautifully wrapped.

I'm thinking maybe it's a good idea If I try to port the Keras model to a Pytorch model. It doesn't look very complicated a priori, and now that we don't depend on TF for MCMC sampling, maybe we don't need to create all these subprocesses and there is no memory leak? This way, the code won't rely on TF at all, not for building the CNN and not for MCMC sampling. What do you think? I honestly don't understand much about parallel programming and all these subprocesses are getting quite difficult.

It looks like the chains can be easily reset and it's possible to load the internal Hamiltonian with a `QuadPotential` object incorporated in [littlemcmc](https://littlemcmc.readthedocs.io/en/latest/generated/littlemcmc.quad_potential.html#littlemcmc.quad_potential). However, I couldn't find a way to obtain this information from an existing chain. Because `littlemcmc` is quite limited and simplistic, If we follow this route I can try to implement a more complete library, maybe `emcee`.

**Comment by grahamgower** [comment]
Over in #24, I shoved the predict() function into its own child process.  When the process exceeds 2GB memory usage, it will exit, and the main process will restart it. The chain sampling is still really slow, so maybe there's something else going on here that is problematic.

Feel free to explore other avenues, like reimplementing with Pytorch.

**Comment by grahamgower** [comment]
Sampling seems much quicker with `target_accept=0.1`! Not sure what to make of that.

**Comment by pabloswfly** [comment]
Great! The code works for me on CPUs, but gets truncated after the first process exit on GPU. I will explore what can be failing right now and try to implement the discriminator model on PyTorch.

Theoretically, lower target acceptance probabilities during the burn-in result in the MCMC behaving more permissive in low-density areas. Maybe a higher ratio of proposals is being accepted but in exchange for sampling robustness.

**Comment by grahamgower** [comment]
I made some improvements and it's running smoothly with GPUs now too. Also, it seems tensorflow uses *a lot* more RAM when using GPUs compared to CPUs (at least, on our GPU server its ~3.7GB just to predict with 2 GPUs in `CUDA_VISIBLE_DEVICES`!)

**Comment by pabloswfly** [comment]
Those are very good news! I think TF memory usage can be limited using `set_memory_growth(gpu, True) ` before initializing the GPU. For me, when I run the `littlemcmc` `hmc` sampler, it looks like the Progress bar is not advancing and samples are not being accepted, even though the gradients are being calculated and I obtain D(x) scores. I may have not implemented the package properly, I will dig into what can be happening later.

I have managed to port the discriminator model from Keras to PyTorch, and it's fully functioning without any memory leak. The `littlemcmc` sampler was behaving also strangely, so I went back on using TF-probability for running HMC and NUTS kernels. I was afraid of conflicts between PyTorch and Tensorflow, i.e. both using  Cuda or cuDNN for tensor operations and blocking each other, but so far is running smoothly. I will fix some issues and pull a request soon.

**Comment by grahamgower** [comment]
Yeah, I also noticed littlemcmc doing strange things. I think the performance seemed better when I trained the discriminator for more epochs, so maybe there's an issue with having a flat likelihood surface? Or generally with calculating the gradients?

**Comment by pabloswfly** [comment]
It doesn't look like we have a flat likelihood surface. Maybe the problem is related to how the gradients are estimated. I've generated a GIF of the current discriminator inference, you can find it here: https://filebin.net/gufxessuqrggzbdk. The cnn was trained with 10,000 genmats, 5,000 with class `y=1` for a fixed recombination rate `r=1e-9` and 5,000 genmats with class `y=0` with a random value. I've realized that, when sampling these random values, I was using a uniform scale between the permitted parameter bounds `(1e-12, 1e-7)`, which resulted in sampling a lot of values from the high end (lots of values near `1e-7`) and just a few from the lower end (few values near `1e-12`). I have fixed that.

I will do the same analysis with the Pytorch model to see how the plots compare.

**Comment by pabloswfly** [comment]
There are no memory leaks in the last version of the software with the PyTorch discriminator so I am closing this thread. 
I will open it up again if the broken pipe error keeps appearing.
